language: android
android:
  components:
   - build-tools-19.0.3
   - android-19
   - platform-tools
   - extra-android-support
   - extra-android-m2repository
jdk: oraclejdk7
before_install:
    - sudo apt-get update -qq
    - git submodule update --init --recursive
